<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Raktim" failures="2" tests="4" name="Test" time="13.73" errors="0" timestamp="2022-04-29T15:42:23 IST">
  <testcase classname="soap.RunByMultipleTestSuite" name="run" time="9.827">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at soap.RunByMultipleTestSuite.run(RunByMultipleTestSuite.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase classname="soap.RunBySingleTestSuite" name="run" time="0.144">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at soap.RunBySingleTestSuite.run(RunBySingleTestSuite.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase classname="soap.RunByTestCase" name="run" time="1.472"/>
  <testcase classname="soap.Runner" name="run" time="2.183"/>
</testsuite> <!-- Test -->
